site_name: Laurent Gil
site_url: https://angegar.github.io
site_description: Laurent Gil web site used to host tutorials
theme:
    name: material
    include_sidebar: true
    icon:
      repo: fontawesome/brands/github
    features:
      - search.suggest
nav:
  - Home: 'index.md'
  - DevOps: 
      - 'Documentation as code': 'devops/doc-as-code'
  - Platform Engineering: 'platform-engineering/README.html'
  - Kubernetes:
    - 'Overview': 'Kubernetes/kubernetes-overview/README.html'
    - 'Basic usage': 'Kubernetes/kubernetes-basics'
    - 'Hands-on': 'Kubernetes/kubernetes-wordpress'
    - 'Blue-green': 'Kubernetes/bluegreen'
    - 'Helm': 'Kubernetes/kubernetes-helm/README.md'
    - 'Ecosystem': 'Kubernetes/kubernetes/'
    - 'Cluster administration': 'Kubernetes/cluster-administration/'
    - 'Security': 'Kubernetes/security'
    - 'Best practices': 'Kubernetes/best-practices/README.md'
  - IaaC:
    - 'Cloud Development Kit': 'cdk/README.html'
  - CI/CD:
    - 'Dagger': 'dagger/README.html'
  - Conferences:
      - 'All Days Devops 2020': 'Conferences/index.md'
      - 'All Days Devops 2021': 'Conferences/alldaysdevops-2021.md'
      - 'All Days Devops 2022': 'Conferences/alldaysdevops-2022.md'


repo_url: https://github.com/angegar/angegar.github.io
repo_name: angegar.github.io
edit_uri: 'edit/main/docs'
remote_branch: gh-pages
google_analytics:
  - UA-10069210-6
  - auto
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - toc:
      permalink: True
dev_addr: 0.0.0.0:8002
plugins:
  - git-revision-date-localized:
       type: date
       fallback_to_build_date: true
extra_css:
  - css/angegar.css

extra:
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#social-links
  social:
    - type: 'linkedin'
      icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/in/laurent-gil/?locale=en_US'
    - type: 'github'
      icon: 'fontawesome/brands/github'
      link: 'https://github.com/angegar'
    - type: 'medium'
      icon: 'fontawesome/brands/medium'
      link: 'https://medium.com/@laurent-gil'
    - type: 'twitter'
      icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/angegar'