name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Markdown Lint
    # Set the agent to run on
    runs-on: ubuntu-latest
    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        #uses: github/super-linter@v3.13.1
        # Workaround for https://github.com/github/super-linter/issues/938
        uses: docker://github/super-linter:v3.13.1
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_MARKDOWN: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          MARKDOWN_CONFIG_FILE: .markdownlint.json
    
  linkCheck:
    name: Links
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@master
      # https://github.com/marketplace/actions/markdown-link-check
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: 'mlc_config.json'

  # spellCheck:
  #   name: Spelling
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@master
  #   - uses: rojopolis/spellcheck-github-actions@0.5.0
  #     name: Spellcheck
  spellCheck:
    name: Spelling
    runs-on: ubuntu-latest
    steps:
    - name: install English dict
      run: |
        sudo apt-get update
        sudo apt-get install -y aspell-en
        pip install 'pyspelling==2.6.1'
    - uses: actions/checkout@master
    - name: Check spelling EN
      run: |
        pyspelling -c .spellcheck.yml
        
  styleCheck:
    name: Style and Voice
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Style check
      uses: errata-ai/vale-action@v2.0.1
      with:
        styles: |
          https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
          https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
  build:
    runs-on: ubuntu-latest
    # container: Docker/Dockerfile
    name: Build and publish
    steps:   
      - name: Checkout code
        uses: actions/checkout@v2 
        with:
            clean: true
            token: ${{ github.token }}

      - name: Copy requirements.txt
        run: cp requirements.txt .github/actions/build

      - name: Build and publish website
        id: build
        uses: ./.github/actions/build
    
    needs: 
    - lint
    - linkCheck
    - spellCheck
